### ISSUE TITLE
Adjustable font size in mobile (iPad) left side pane

### ISSUE THREAD

**Issue by davebhc71** [primary-theme/obsidian#10]
Do you plan on having a companion Plugin (e.g. Minimal) to customize various Theme font size options, especially the left Settings Pane, and

THIS IS ONE BEAUTIFUL THEME!!!!!!!!

**Comment by ceciliamay** [comment]
AAAAA!! Thank you so so much for the kind words!! 🙏

I'm still thinking about the pros and cons of creating a separate plugin for customization vs. just using the Style Settings as a way to allow for customization (if you know the difference please let me know!!). I appreciate your suggestion!!

Quick question - what particular part of the UI do you want font-size changed? Do have a specific part you want changed (i.e. just the left side pane, not the right side pane; or all UI font-sizes; etc.)? I've been thinking about how specific I will be building the customization and finding a good middle-ground between too much and too little, so your answer to this will be of great great help 🙏

**Comment by davebhc71** [comment]
Thanks for the reply. I primarily use Obsidian on the iPad Air. So I’m very concerned of screen real estate. My preference is for the KISS principle in regard to font sizes. Just two settings, one for for both left and right panes and the second for the editor/Preview (or NOW WYSIWYG). You’ve done a beautiful job with everything else. Colors MAYBE later, but that’s less important to me. Thanks for asking. Hope you decide to offer that. @Kepano offers that option with his side plugin for the Minimal theme.

**Comment by ceciliamay** [comment]
Primary 2.7.0 is a refreshed version of the theme and comes with tablet and phone compatibility! The update addresses this issue. 

![Image](https://github.com/primary-theme/obsidian/assets/90643719/2e4b9b31-3c45-4a8e-81f7-7a58ad195422)
