### ISSUE TITLE
 Side Dock Ribbon + Status Bar

### ISSUE THREAD

**Issue by miharekar** [primary-theme/obsidian#104]
Reading 1.4.4 release notes I had an idea that it might be an interesting idea to have status bar inside the right ribbon.

This is a very crude CSS transform to illustrate the point:

<img width="293" alt="CleanShot 2022-03-31 at 09 57 41" src="https://user-images.githubusercontent.com/986645/161006297-17e3a704-a506-4ca7-9240-152863354dae.png">

WDYT?

**Comment by ceciliamay** [comment]
Ooooh this is an interesting idea! How do you feel about the readability if we transform it that way? I will test this out over a few days to get a personal feel about the functional aspects but this is a really good suggestion. Got me thinking.

OH i had another idea while typing - maybe we could also do a, "Show on Hover" status bar - it's like the side dock ribbon Show on hover, but for the Status Bar.

**Comment by miharekar** [comment]
Yeah, I don't know. I think it would be all right. But I guess I'm used to reading sideways from the sliding panes plugin 😅

**Comment by ceciliamay** [comment]
Ahaaa! Right right. I forgot about that plugin. I'll add that on the next update ;) Thank you for the suggestion!!

**Comment by ceciliamay** [comment]
Ribbon Styling

- [ ] Slide out on Hover
- [ ] Floating Ribbon
- [ ] Opacity at Rest
- [ ] Opacity on Hover

Additional Status Bar Styling

- [ ] Slide out on Hover
- [ ] Status Bar Orientation (Horizontal / Vertical)
- [ ] Status Bar Position (Left / Right )
- [ ] Status Bar Offset
- [ ] Background
- [ ] Border Width
- [ ] Border Color
- [ ] Border Radius
- [ ] Opacity at Rest
- [ ] Opacity on Hover

**Comment by miharekar** [comment]
Wooo 🥳
