### ISSUE TITLE
Question about Emojis

### ISSUE THREAD

**Issue by Write** [primary-theme/obsidian#110]
I stumbled upon the latest release images :

![image](https://user-images.githubusercontent.com/541722/161296323-acb03de4-0d95-4b3f-9042-5a3b033826b2.png)

And found that icons were much nicer than mine, which use the default macOS emojis.

Current result for me : 

![CleanShot 2022-04-01 at 17 39 12](https://user-images.githubusercontent.com/541722/161296519-a90116e6-6aa1-4e18-9315-38f11dfdc93d.png)

Though, theme's custom icons work great for me : 
![CleanShot 2022-04-01 at 17 39 51](https://user-images.githubusercontent.com/541722/161296590-26e99198-d696-4f97-9933-e4064ae7decd.png)

Thanks a lot, amazing work.

**Comment by ceciliamay** [comment]
Oooh, so that's how they look like on MacOS 👀 - these are Windows 11 Emojis! It's odd that they don't seem to create a "space" despite having added one 🤔

**Comment by Write** [comment]
Yeah, the result is hideous, I really thought you had custom one, well anyway... haha

**Comment by ceciliamay** [comment]
I will consider changing them into icons so that they have a more universal look (no to hideous Mac emojis 😂) - but that will probably be after I complete all the sections in all my planned customizations update. 
Thanks for reporting!! This was an interesting one!! 😄 I'll keep this open just as a reminder.

**Comment by Write** [comment]
Just do add informations : The emoji issues is with all theme on macOS (at least for me).

**Comment by ceciliamay** [comment]
the emojis have been replaced with icons in the 2.7.0 refresh/rebuild update! this makes them consistent across platforms, including mobile devices.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/ef62748a-2da6-439d-879b-b12fbc3d8ff9)
