### ISSUE TITLE
Visual Bug When Embedding in Callout Blocks

### ISSUE THREAD

**Issue by Signynt** [primary-theme/obsidian#112]
![Screenshot 2022-04-04 at 22 41 26](https://user-images.githubusercontent.com/67801159/161628548-9db1a19d-496b-4f88-8424-5e73d9cf798b.png)

```
> [!klinik] Alpha Blockade
>  ![[Alpha Blockade]]
```

**Comment by ceciliamay** [comment]
this issue no longer exists in the new refreshed/rebuilt Primary 2.7.0! consider updating your theme!!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/782cd8ef-d407-461a-84fe-5c8c29b93a61)
