### ISSUE TITLE
make card buttons for kanban plugin smaller or hide

### ISSUE THREAD

**Issue by h0uter** [primary-theme/obsidian#115]
Hi amazing theme!

Is it possible to make the UI buttons for the kanban plugin smaller?
I like to keep a narrow  (180px) kanban in my right sidebar, there it's really out of proportion.
Or make it possible to disable them? Since right-click also gives access to all the options.
Either by default or through the style settings plugin.

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/40892865/162004378-1cf6544d-7d6a-4749-9220-9f3d9275d759.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/40892865/162003331-2d519ea4-a359-4882-8725-b5192a2361d3.png">

Keep up the amazing work!

**Comment by ceciliamay** [comment]
the cards in kanban are now styled appropriately in the new Primary 2.7.0 refresh/rebuild! consider updating your theme.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/3c97ef99-94db-46ce-8eb3-b5e16df061b6)
