### ISSUE TITLE
Include version number somewhere

### ISSUE THREAD

**Issue by danielnichols** [primary-theme/obsidian#118]
It would be useful if there was somewhere that we could see what version of the theme is installed, like in the style settings or the installed themes window. It's not hugely important, but it can be useful to compare the installed version to the latest version.

**Comment by ceciliamay** [comment]
I am currently waiting on Obsidian's official implementation of [theme versioning](https://trello.com/b/Psqfqp7I/obsidian-roadmap)! 

![image](https://user-images.githubusercontent.com/90643719/163204736-72fc0990-e2ca-496d-9a68-bcf6567f7e20.png)

I will keep this open for others to see, and will update this thread once Obsidian pushes out the update. thank you for the suggestion!!

**Comment by ceciliamay** [comment]
This has been added to the Obsidian v1.0+ when you go to the theme's page inside the app. so I will be closing this now. Thank you for your inputs 🙏
