### ISSUE TITLE
Keep the pin visible

### ISSUE THREAD

**Issue by miharekar** [primary-theme/obsidian#127]
I find pinning notes quite useful, however I forget I can do it. So I wanted to have the pin icon always visible.

<img width="66" alt="CleanShot 2022-05-04 at 09 12 46" src="https://user-images.githubusercontent.com/986645/166636832-85ed21d4-f2e7-4be0-9874-7f87e978b3f5.png">

My hacky way:

```
.view-action.mod-pin-leaf:not(.is-active) {
  display: block !important;
  color: var(--color-l-gray-50) !important;
}
```

I'm sure you can come up with a better solution. Probably with an option via style settings?

**Comment by ceciliamay** [comment]
this is now properly styled in the new Primary 2.7.0 refresh/rebuild!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/41acf6fd-022d-49b6-a2af-bab4c62c0386)
