### ISSUE TITLE
no emphasis/link colors within block quotes in editing mode

### ISSUE THREAD

**Issue by mrdeevid** [primary-theme/obsidian#133]
I like to use block quotes a lot with formatted text inside (bold, italics, links, etc.). I really like them in preview mode using your theme, it's so pretty!
However, when I am in editing mode, all the text within a block quote is blue. So, even bold text, links, etc. stay stay blue instead of their usual colors that you see in preview mode. I work in editing mode 95% of the time and I would like to see these colors again within block quotes like you would in preview mode instead of all blue. Is that possible? Many thanks!

**Comment by mrdeevid** [comment]
Hi @ceciliamay !

Thank you for suggesting the markdown formatting! Indeed, the texts in my block quotes were always fully encapsulated with '_' making it a fully italics text; which would explain the blue color. 

I noticed that the text within block quotes are already in italics by default. This is great! This resolves the blue coloring that I see all the time.

However, after playing with the formatting within block quotes, I'm seeing other related issues. I'm demonstrating this with each emphasis formatting in separate block quotes below.

This is what I'm seeing in editing mode (you can also see how I formatted the text with MD):
![primary_editing mode](https://user-images.githubusercontent.com/79302379/168321300-969af771-898c-441d-988e-6419e35938cd.png)

- As you can see, the color for resolved links are still black instead of yellow.
- Text that is both bold and in italics is still blue instead of green (see reading mode).
- The text with mixed italics and bold formatting does not appear in both colors (blue and red). I know I could resolve this by writing `*italics and* **bold**`, but I don't know which one is standard markdown style or something to consider to fix?

And this is what I'm seeing in reading mode:
![primary_reading mode](https://user-images.githubusercontent.com/79302379/168321046-a056cde0-1c26-42dc-b0ed-669c4ff51af6.png)

I hope this is a clear post and something you can do something about, even if it's a partial fix! 😊

**Comment by ceciliamay** [comment]
thanks for this clear report, @mrdeevid !! i'll look into what i can do 😄

**Comment by ceciliamay** [comment]
this is resolved in the newest update for Primary! 2.7.0 is a rebuilt/refreshed version of Primary. consider updating your theme!
