### ISSUE TITLE
Brown Highlight on Link Hover

### ISSUE THREAD

**Issue by Carnage-A-Sada** [primary-theme/obsidian#136]
Hi there! I love this theme and have been very much enjoying the updates. Since the update, however, I've noticed that whenever I hover over a link while in Reading mode, I get a dark brown highlight that I would prefer to remove but am not sure how to. Would you be able to let me know how to get rid of that? It doesn't really fit with the colors I'm using and makes things difficult to read.

**Here is what it looks like without the highlight on hover:**
<img width="95" alt="image" src="https://user-images.githubusercontent.com/104965153/168923956-ff523dc1-742c-4e7a-8c29-8097e62d9dd6.png">

<img width="122" alt="image" src="https://user-images.githubusercontent.com/104965153/168923864-e7a8441f-1936-48f2-a754-3986ddb975ff.png">

**Here is what it looks like with the highlight on hover:**
<img width="134" alt="image" src="https://user-images.githubusercontent.com/104965153/168923667-b7bc26e5-3295-4d81-a72a-5a0ee1efcf48.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/104965153/168923790-87f01672-894b-49bd-a4ba-3e492df18dfb.png">

**Comment by ceciliamay** [comment]
Hello there! I have not applied this styling - specifically I don't apply a background color when hovering links. Checking the theme on my developer vault, it seems that the highlighted links work fine in both edit and reading mode:

![issue on highlight](https://user-images.githubusercontent.com/90643719/168933810-47bc5426-f970-4bbd-b87b-d0fcc3949bc7.gif)

if you are using a custom snippet to color your highlights, I suggest looking at them and seeing if they style hover states with a different background color! let me know if this works!

**Comment by ceciliamay** [comment]
Hey there @Carnage-A-Sada !! Does the issue still persist? Have you tried the suggestions mentioned above? Let me know soon!
