### ISSUE TITLE
Bad font rendering

### ISSUE THREAD

**Issue by stackingflow** [primary-theme/obsidian#137]
Primary:
![Screenshot 2022-05-19 at 7 38 19 PM](https://user-images.githubusercontent.com/47140829/169313674-8f320166-079b-441f-8ced-3398553cdc39.png)

Default Dark:
![Screenshot 2022-05-20 at 11 07 27 AM](https://user-images.githubusercontent.com/47140829/169458034-2f4257da-f369-48c5-9ad8-b92b8dda2925.png)

LYT:
![Screenshot 2022-05-20 at 11 08 27 AM](https://user-images.githubusercontent.com/47140829/169458143-26e7a5ba-6c56-4977-8732-29ded673de0e.png)

(Click to expand the image for better view)

Font rendering is not like the default theme, not sure if am I the only one who is facing this issue. No custom css, everything is default.
It seems like the font is thinner as compared to the screenshot from GitHub readme file.

**Comment by ceciliamay** [comment]
Thanks for reporting this @stackingflow ! Does this issue still persist?

On my end, it's looking okay. I've actually also applied CSS font optimizations so I am not sure what's causing this. Have you tried updating or reinstalling the theme?
![image](https://user-images.githubusercontent.com/90643719/184345998-abf73136-c122-4c77-81fa-88124b740f1d.png)

**Comment by ceciliamay** [comment]
This issue will be closed. The bad font rendering is probably due to the quality of Karla as a font. I have decided to change the default font to Inter (with alt settings on too), and leave Karla as an option in the Style Settings. This change will be in the coming update. Thank you for reporting 🙏
