### ISSUE TITLE
Dataview Border On Hover

### ISSUE THREAD

**Issue by 702573N** [primary-theme/obsidian#138]
I would like to disable the border on hovering over Dataview objects with "Style Settings" Plugin.

**Comment by aukef** [comment]
+1

When hovering over a dataview object with Tasks (from the task plugin, using ```tasks .... ```,  the CSS shows a border and "Edit this block" button in the topleft corner. This overlaps with the checkboxes from the task plugin

![image](https://user-images.githubusercontent.com/3624855/171835073-6361d529-2092-46c5-aaac-3b4b78ef3b91.png)

I would like the option to disable the border and move the edit button to the topright or even bottomright.

**Comment by ceciliamay** [comment]
all embeds do not have a border now on the refreshed/rebuilt Primary 2.7.0! only the "edit this block" button shows up.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/a5bf1d2a-b1ab-4b53-a79f-f55f94939612)
