### ISSUE TITLE
Align ordered lists numbers, unordered lists bullets, and checkbox lists

### ISSUE THREAD

**Issue by raisabelatrix** [primary-theme/obsidian#139]
This is how lists look like in default obsidian theme with all plugins off:

![image](https://user-images.githubusercontent.com/82343091/170879165-46053ae4-34d4-467d-ac21-0a8e4302f9f0.png)

See how the numbers, bullets, and checkboxes align so well?

Now, this is what it looks like in the primary theme even with all plugins off:

![image](https://user-images.githubusercontent.com/82343091/170879228-9f22013d-66b5-4914-bcf1-fea0db3f50fd.png)

The alignment is just all over the place... the only thing aligned are the collapse indicator arrows

**edit:** looking at this screenshot some more, I think even the arrow alignment looks a little off

**Comment by ceciliamay** [comment]
This is probably fixed due to the Obsidian 1.0+ update. I will ensure the proper alignment doesn't get overridden in the Primary 2.0 update! I will close this now. Thank you so much for posting this 🙏
