### ISSUE TITLE
Custom Cursor no longer supported in 14.15

### ISSUE THREAD

**Issue by Barthcbb** [primary-theme/obsidian#141]
This is just a heads-up that the CSS properties for customizing the cursor have been removed in Obsidian's latest build. That said, Primary's custom/colorful cursor is no longer working, save for mouse selections.
<img width="140" alt="image" src="https://user-images.githubusercontent.com/99547827/173343622-3c720ebe-76b9-4e38-8735-d34a5e7584ab.png">

<img width="143" alt="image" src="https://user-images.githubusercontent.com/99547827/173343571-5e881fda-cec6-4ed2-bc50-f66d6101aa72.png">

It's a pity because I like it. 🫤

Here are some reference posts from the forum:
- [Css Cursor properties stopped behaving as expected after 0.14.15 Update](https://forum.obsidian.md/t/css-cursor-properties-stopped-behaving-as-expected-after-0-14-15-update/38674/2)
- [Cursor Styling since 0.14.15](https://forum.obsidian.md/t/cursor-styling-since-0-14-15/38721/2)

**Comment by ceciliamay** [comment]
Hey there @Barthcbb - thank you for the kind words and I apologize for the late reply!! I do like the color cursor too. Does the issue still persist? Looking at my Obsidian now it seems to work as expected. Let me know if it still isn't working on your end!

**Comment by Barthcbb** [comment]
> Let me know if it still isn't working on your end!

Hi, no worries at all! I'm on Obsidian 15.9 now and got the same situation: the cursor is darker, taller and thinner while typing (or standing by), and it's lighter, shorter and thicker when selecting texts.

Here's a gif comparing it:
![primarycursor](https://user-images.githubusercontent.com/99547827/184370784-357a89c7-3603-48ff-9bfb-0f643a16fcd2.gif)

**Comment by ceciliamay** [comment]
I will be closing this issue for now due to the changes made with that are out of our hands (i.e. CM6 updates, Obsidian updates, etc.). I will see if this can be added in the upcoming update for Primary 2.0 but if it doesn't, I will no longer pursue this. Thank you for filing this nonetheless! 🙏
