### ISSUE TITLE
Obsidian sidebar got cut off on iPad Pro

### ISSUE THREAD

**Issue by dannuen** [primary-theme/obsidian#149]
Hi, love what you are doing with the theme.

Since I mainly use Obsidian on my iPad, I notice the sidebar got cut off at the bottom. It’d be great if you could fix it to fit it on iPad as well.
![75872DDE-3896-421E-A34B-D1776773BF24](https://user-images.githubusercontent.com/111210530/184520136-9dc9db40-a371-49c0-9c07-9789feec8c3d.png)

**Comment by cjolson** [comment]
Yes please! 🙏
I have the same issue. Came here to see if there was a fix.

**Comment by ceciliamay** [comment]
this issue no longer exists in Primary 2.7.0! this version brings a rebuilt and refreshed version of the theme. consider updating!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/53e41b8d-b496-49af-817e-d6f39c6052e8)
