### ISSUE TITLE
Kanban view doesn't factor vertical scrollbar in

### ISSUE THREAD

**Issue by putzwasser** [primary-theme/obsidian#151]
The Kanban Plugin view doesn't factor the width of the vertical scrollbar in if you [use metadata fields of the list items](https://matthewmeye.rs/obsidian-kanban/Settings/Linked%20page%20metadata/):

![image](https://user-images.githubusercontent.com/26040044/184866647-020ebdb1-fde1-4d41-984e-fc6cd2217b99.png)

This screenshot shows the text from the metadata field `Reason` and the progress bar overflow the available width of the card.

That is because of the presence of the vertical scrollbar. This screenshot shows a perfectly fine rendered list item with metadata as long as there's no vertical scrollbar:

![image](https://user-images.githubusercontent.com/26040044/184867352-9c9f2746-8fd3-4d3b-9f1d-9bf2829091f8.png)

**Comment by ceciliamay** [comment]
Hey @putzwasser !! Thank you so much for letting me know of this issue. I don't personally use the Kanban plugin hence why it isn't officially supported so I apologize for the bugs. That being said, I am not familiar with the roundabouts of the plugin - can you send me the markdown syntax of your note so I can replicate it on my end?

Thank you so much in advance 🙏

**Comment by putzwasser** [comment]
I guess, it's easiest if you copy the sample vault from https://bagerbach.com/blog/projects-and-goals-obsidian ^[1]

[Link to zipped vault](https://github.com/chhoumann/DemoVault/archive/refs/heads/main.zip)

You need the [Obsidian kanban plugin](https://github.com/mgmeyers/obsidian-kanban), too.

You might need to drag and drop some list items into one list until the vertical space is used up, then you should be able to trace the bug.

^[1] Side note: This page made me aware of the [table-to-cards feature](https://github.com/kepano/obsidian-minimal#cards) from [the minimal theme](https://github.com/kepano/obsidian-minimal). Maybe you got the time and energy to implement this as well. It would be super cool.

**Comment by putzwasser** [comment]
I guess, it's easiest if you copy the sample vault from https://bagerbach.com/blog/projects-and-goals-obsidian ^[1]

[Link to zipped vault](https://github.com/chhoumann/DemoVault/archive/refs/heads/main.zip)

You need the [Obsidian kanban plugin](https://github.com/mgmeyers/obsidian-kanban), too.

You might need to drag and drop some list items into one list until the vertical space is used up, then you should be able to trace the bug.

^[1] Side note: This page made me aware of the [table-to-cards feature](https://github.com/kepano/obsidian-minimal#cards) from [the minimal theme](https://github.com/kepano/obsidian-minimal). Maybe you got the time and energy to implement this as well. It would be super cool.

**Comment by ceciliamay** [comment]
hey folks! i know this is a very old issue, but with the new v2.8.0 of primary and tons of update to obsidian since then, i wanted to check in to see if this issue still persists on your end. if not, i will close it in a few days.

as always, i appreciate all the help!
