### ISSUE TITLE
Horizontal scrollbar in quick switcher

### ISSUE THREAD

**Issue by memeplex** [primary-theme/obsidian#152]
A weird horizontal scrollbar appears when opening the quick switcher, then suddenly goes away.

https://user-images.githubusercontent.com/2845433/185278674-7f14d22a-a000-460f-b3de-984f3de194d9.mov

This doesn't happen with either the default theme or Minimal theme.

Obsidian 0.15.9 (installer 0.15.9)

---

PS: Primary theme is gorgeous!

**Comment by memeplex** [comment]
I realized the same happens in the command palette.

**Comment by ceciliamay** [comment]
this issue is fixed with the new refreshed/rebuilt Primary 2.7.0 update! we now have a very smooth, properly styled quick switcher - no horizontal scrollbars! consider updating your theme :)
