### ISSUE TITLE
Note title truncated on Android version

### ISSUE THREAD

**Issue by aquatix** [primary-theme/obsidian#155]
On my phone (Pixel 5) and Chromebook tablet (HP X2 11) I use the official Android version of Obsidian with Primary. This looks and works great (thanks for this beautiful and functional theme!).

One thing is amiss, which works fine on the desktop version, and that's the note title. This fades out way early, with often lots of room to spare to the right of it.

See for example the attached screenshot from my phone.

![Screenshot_20220830-181625.png](https://user-images.githubusercontent.com/629545/187488927-4f93934e-29ee-4bdc-a72a-ed7becaf0021.png)

Let me know if you need more information or if I can test something.

Thanks in advance!

**Comment by dsent** [comment]
Can confirm this happens to me too.

**Comment by michinoke** [comment]
```css
.is-mobile .view-header-title {
  width: 100%;
}
```
This seems to fix it for me. Haven't noticed it break anything yet.

**Comment by aquatix** [comment]
@michinoke that works great here; saved it as a snippet and the titles show fine now, thanks for figuring it out!

**Comment by ceciliamay** [comment]
this issue no longer exists in the newly refreshed and rebuilt Primary 2.7.0! consider updating your theme :)

![Image](https://github.com/primary-theme/obsidian/assets/90643719/4446d284-a291-469e-a9b9-bb9ce411de0f)
