### ISSUE TITLE
Menu Scroll Bug On Windows

### ISSUE THREAD

**Issue by Notkeltan** [primary-theme/obsidian#163]
Hiya Cicilia!

Since I've updated Obsidian scrolling isn't functional in menus. I can get around it with hotkeys and search currently.

Hope this helps you out! Good luck with this big Obsidian change!

**Comment by KristineWatson** [comment]
🙏same problem ！I love this theme so much！can you fix this？

when i open plugin “projects” i can’t scroll down 👇
 ![图片](https://user-images.githubusercontent.com/92555979/211514943-c2762732-c899-48d1-a6fe-0c57493e10f7.png)

but i can do it when using other themes
![图片](https://user-images.githubusercontent.com/92555979/211515986-1ce486ad-0c07-4b90-8b5c-c0a2f11a73ce.png)

**Comment by ceciliamay** [comment]
this issue no longer exists in the newly refreshed/rebuilt Primary 2.7.0! consider updating your theme :)

![Image](https://github.com/primary-theme/obsidian/assets/90643719/c21831a1-4de5-4982-82eb-28168bfc1f19)
