### ISSUE TITLE
1.0 compatibility

### ISSUE THREAD

**Issue by kedanli** [primary-theme/obsidian#164]
Hi,

thank you a lot for this great theme. I love it.
Will there be a new version which is compatible with version 1.0? Looks not so nice atm... :)

**Comment by ceciliamay** [comment]
yes there will be!! i apologize for not updating it yet but be glad to know that i have started working on obsidian 1.0 😄

**Comment by kedanli** [comment]
🥳 such great news!!!
Thank you very much. 😃

**Comment by pgyogesh** [comment]
Yeah... Waiting for this... Thank you so much

**Comment by putzwasser** [comment]
Thanks for working on it!

**Comment by aquatix** [comment]
#154 was opened for basically the same issue, but then "1.0" was still called "0.16". Just for the people looking for updates :)

**Comment by putzwasser** [comment]
@ceciliamay Maybe you could publish incremental fixes, instead of one huge update that fixes everything. That way we could enjoy using primary on 1.0 instead of temporarily having to switch to another theme.

**Comment by GeorgeGo** [comment]
> @ceciliamay Maybe you could publish incremental fixes, instead of one huge update that fixes everything. That way we could enjoy using primary on 1.0 instead of temporarily having to switch to another theme.

Huge fan of this idea, other themes just don't have the right ideas around color accenting, contrast, and space that primary does so it's been somewhat painful to use alternate themes for the time being.

**Comment by Rainvoo** [comment]
> yes there will be!! i apologize for not updating it yet but be glad to know that i have started working on obsidian 1.0 😄

Good news！I quite like your theme! I am looking forward to the new version

**Comment by erickvr2k** [comment]
me too! i'm looking forward to see the new version for Obs 1.0

**Comment by hellerbarde** [comment]
@ceciliamay I started a branch for the upgrade. You can find it here: https://github.com/hellerbarde/obsidianmd-theme-primary/tree/feature/upgrade-theme-to-obsidian-1.0

- converted all the --scale-x-y to the --size-x-y that are used in the official themes. 
- I tried to fill the color variables in app.css with the versions that exist in Primary. 
- I commented out all the files that I either didn't/couldn't check yet. 
- Currently working on the title-bar/header-bar. It's honestly a little confusing, because I'm neither an Obsidian theme author nor very good at CSS... :D 

Feel free to use any or all of my changes, or contact me if I should explain any of my decisions I made, or disregard all of this.

Thanks for your efforts and let's hope we can soon use the comfortable warm coziness that is Primary. :heart:

**Comment by hellerbarde** [comment]
And anyone else that wants can use it too, btw. Just download the obsidian.css file and chuck it into your themes folder (rename it to something like "Primary Development") and off you go.

**Comment by majdf4** [comment]
This theme is absolutely beautiful but I wanted to ask if there is an ETA? If you can't provide one that is completely fine

**Comment by evanrelf** [comment]
Y'all just calm down and be patient, it'll be released when it's ready and no sooner.

**Comment by royvanderwoning** [comment]
> it'll be released when it's ready and no sooner

Mind=blown.

**Comment by ArneNostitz** [comment]
i just put me here so that I am front row for this wonderful piece of screendesign :)

**Comment by erickvr2k** [comment]
I dont mean to bother your work, but is there any updates about the development of the new version?

**Comment by jorgediazjr** [comment]
Will it be out by Christmas ?

**Comment by Write** [comment]
I'd encourage everyone to [Buy her a coffee](https://ko-fi.com/ceciliamay) to keep motivations up.
Keeping up an Obsidian's theme isn't a light work, specially with 1.0 update.

**Comment by cppjames** [comment]
@ceciliamay It's wonderful that you're working on an update for the new version of Obsidian. Many of us are regularly checking this thread for announcements. Even the tiniest notice that progress is being made would assure Primary users that the wait is worthwhile. Thank you for this fantastic theme!

**Comment by jorgediazjr** [comment]
Is this still being worked on ?

**Comment by neito5** [comment]
Girl, this is just a color scheme, not the Apollo program ☠
Thx for the work you've done, but we could have ported this to obsidian-minimal in 2hrs, instead of people checking this thread for 4 months because you won't say anything - while working on the Thunderbird plugin nobody asked for.

**Comment by jwagon** [comment]
> Girl, this is just a color scheme, not the Apollo program ☠ Thx for the work you've done, but we could have ported this to obsidian-minimal in 2hrs, instead of people checking this thread for 4 months because you won't say anything - while working on the Thunderbird theme nobody asked for.

WTF?

If it's so easy, why don't you offer to help instead of running your mouth like a punk?

**Comment by ArneNostitz** [comment]
> Girl, this is just a color scheme, not the Apollo program ☠
> Thx for the work you've done, but we could have ported this to obsidian-minimal in 2hrs, instead of people checking this thread for 4 months because you won't say anything - while working on the Thunderbird theme nobody asked for.

how disrespectful can you be? if it takes you two hours, please do it. she is working on this for free and can choose whatever she likes to do. 
please @ceciliamay, take your time and know that we (or at least I) are more than greatful that you made this beautiful theme

**Comment by Kazeheki** [comment]
> Girl, this is just a color scheme, not the Apollo program ☠ Thx for the work you've done, but we could have ported this to obsidian-minimal in 2hrs, instead of people checking this thread for 4 months because you won't say anything - while working on the Thunderbird theme nobody asked for.

You know this is GitHub, right? Open a PR if you can and want to help. I just saw there is a draft PR where people are helping and discussing issues they have with porting this theme.

**Comment by kparkov** [comment]
> Girl, this is just a color scheme, not the Apollo program ☠ Thx for the work you've done, but we could have ported this to obsidian-minimal in 2hrs, instead of people checking this thread for 4 months because you won't say anything - while working on the Thunderbird theme nobody asked for.

@neito5 If you expect priority customer service, first you need to find a product paid with your money. This product is paid with gratitude and community support. You don't get to expect anything, you can only hope or help out.

**Comment by kl0907** [comment]
seems like the theme is still buggy display wise on the latest version of Obsidian (1.1.16). I'm loving the theme so far, and whilst it's still very much functional, any update in the near or far future would be appreciated :)

**Comment by cekkeen** [comment]
For anyone waiting, I am using the Anuppuccin theme as a replacement. This theme can be customized to look similar, and in my opinion, better than this theme. Additionally, for those who use the ribbon autohide, I am utilizing the commander plugin to create a button that allows me to hide it when it's not needed.

**Comment by putzwasser** [comment]
@cekkeen Thanks for the hint. how would you customize the theme?

**Comment by cekkeen** [comment]
> @cekkeen Thanks for the hint. how would you customize the theme?
go to the official  obsidian discord
go to #showcase-notes
search for:  "trevor#2959 You can use a snippet to achieve that" (If you are reading this now, scroll up a little and it's there)
ask him any question you have, and also there's a lot of information on how to customize anuppuccin on youtube and the obsidian discord.

**Comment by cekkeen** [comment]
> @cekkeen Thanks for the hint. how would you customize the theme?

go to the official  obsidian discord
go to #showcase-notes
search for:  "trevor#2959 You can use a snippet to achieve that" (If you are reading this now, scroll up a little and it's there)
ask him any question you have, and also there's a lot of information on how to customize anuppuccin on youtube and the obsidian discord.

**Comment by danielamaya** [comment]
I've forked the repo and made some modifications to get this working on my MacBook. Here's the repo: https://github.com/danielamaya/obsidianmd-theme-primary.

I have no idea how well this works on mobile, Linux, Windows or any other platform. I have only tested on my MacBook. I am not a web developer, so my changes are probably not the greatest. I just hacked things together to get it working on my Mac.

I am open to any pull reqs. anyone wants to do. I can test on Linux and Mac, but not on mobile. I may take some time at some point to actually go through this in more detail, clean things up, and so on, but for now I'm strapped on time and this works for me.

**Comment by ceciliamay** [comment]
![Image](https://github.com/primary-theme/obsidian/assets/90643719/3f3d2f4b-4c16-4d6b-a521-3bf8bdbb0f3f)

Mockup done. Coding now.

**Comment by GeorgeGo** [comment]
Looks amazing! Super excited to get back into using Primary. Great update!

**Comment by kathynhi** [comment]
I'm sooo excited!!! Thank you for all your hard work. I've tried many, many themes. Primary and Blue Topaz are at the top for me.

**Comment by ceciliamay** [comment]
hello! Primary 2.7.0 (made to be compatible with Obsidian 1.0+) is out now on the theme store!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/c6a3fe1d-e085-4823-8155-30ba5aceaebc)


read the public announcement here: https://primarytheme.substack.com/p/primary-for-obsidian-is-now-publicly
