### ISSUE TITLE
Theme doesn't work for latest Obsidian update (v1.0.0)

### ISSUE THREAD

**Issue by anixn** [primary-theme/obsidian#165]
With the new layout, all the Icons are squished.

**Comment by KosmosisDire** [comment]
There is already an issue open for this btw: https://github.com/ceciliamay/obsidianmd-theme-primary/issues/164

**Comment by ceciliamay** [comment]
hey folks! Primary 2.7.0 is out now - available on the obsidian theme store - and is a fully refreshed version of Primary! you can view the complete release notes here: https://github.com/primary-theme/obsidian/releases/tag/v.2.7.0
