### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by pengzhenghao** [primary-theme/obsidian#166]
I think it would be helpful to include a section in README to teach user how to install the theme. Nice theme, thanks!

**Comment by Lisandra-dev** [comment]
Hello.
The theme is incompatible with 1.0, so it was removed from the store until the Legacy tag is removed.

**Comment by feedhopper** [comment]
Are there plans to make it compatible?

**Comment by erickvr2k** [comment]
sure @feedhopper many people are working on it. Just be patient.

**Comment by feedhopper** [comment]
thanks for the update. I wasn't aware of this involving many people.

**Comment by vitovt** [comment]
Subscribe. It is not clear how to install.
As I understood, after downloading in should be compiled before copying to .obsidian folder
But how to compile it ?

**Comment by dedebenui** [comment]
just copy the `obsidian.css` file into `<your vault>/.obsidian/themes`. You may need restart obsidian for it to show up

**Comment by JDRanpariya** [comment]
I would like to contribute and make it working. Is there anyone who can help me with it?

**Comment by SalahAdDin** [comment]
It is not available from `Settings > Appearance > Themes`.

**Comment by erickvr2k** [comment]
> It is not available from `Settings > Appearance > Themes`.

there is no new release for the new Obsidian 1.1.X

**Comment by MHolkamp** [comment]
Is there any update coming for version 1.x.x?

**Comment by ceciliamay** [comment]
![Image](https://github.com/primary-theme/obsidian/assets/90643719/43cde0bc-7106-44f1-9930-8bea4841ce87)

Mockup done. Coding now. Will update the READMEs and add better wikis after.

**Comment by Tejeev** [comment]
Is there an issue tracking this?  I thought [#178](https://github.com/primary-theme/obsidian/issues/178) would be it but that was closed.  I guess this is the one to follow?

**Comment by ceciliamay** [comment]
The theme is currently available in beta through my [Ko-fi page](https://dub.sh/primary/ko-fi)! It's currently in beta while being in the rebuild phase for Obsidian 1.0+ compatibility. It'll be out for free for public use once it's out of beta!

**Comment by Tejeev** [comment]
@ceciliamay ah!  Could we re-open #178 or open a new issue to track this where we can link to your ko-fi page?  I was wondering about where the issue to track this was because that's usually where we find information like this.

**Comment by ceciliamay** [comment]
hey folks! Primary - newly rebuilt and refreshed - is now available publicly in the Obsidian Theme Store! You can read the full release notes here: https://github.com/primary-theme/obsidian/releases/tag/v.2.7.0

[How to Install](https://github.com/primary-theme/obsidian?tab=readme-ov-file#install-official-release)

![Image](https://github.com/user-attachments/assets/d7eceb90-c08c-4558-b9f6-acbf2b2bbb5d)

![Image](https://github.com/user-attachments/assets/e6079027-1794-4956-a7f8-a795fe251d85)
