### ISSUE TITLE
Bullets - purely cosmetic

### ISSUE THREAD

**Issue by TShby** [primary-theme/obsidian#167]
After the Obsidian update, all of my bullets have a little line (or maybe a dot) below them in the editor preview mode.

![image](https://user-images.githubusercontent.com/116390293/197284895-2c905bd8-b3ec-404c-8bbe-5eec06197091.png)

Purely a cosmetic problem - no functionality issues.

**Comment by jesugq** [comment]
Locate and remove these declaration blocks in themes/Primary/theme.css:

```
.markdown-source-view.mod-cm6 .list-bullet:after {
  content: "-";
  font-family: var(--font-monospace-theme);
  font-size: 1.25em;
}
.markdown-source-view.mod-cm6 .cm-list-2 .list-bullet:after {
  content: "•";
}
.markdown-source-view.mod-cm6 .cm-list-3 .list-bullet:after {
  content: "◦";
}
```

**Comment by gabb0z** [comment]
Thank you @jesugq !!

**Comment by pckc** [comment]
> Locate and remove these declaration blocks in themes/Primary/theme.css:
> 
> ```
> .markdown-source-view.mod-cm6 .list-bullet:after {
>   content: "-";
>   font-family: var(--font-monospace-theme);
>   font-size: 1.25em;
> }
> .markdown-source-view.mod-cm6 .cm-list-2 .list-bullet:after {
>   content: "•";
> }
> .markdown-source-view.mod-cm6 .cm-list-3 .list-bullet:after {
>   content: "◦";
> }
> ```

after doing this I ended with a bullet point crossed by a line. Is that the intended pattern of theme?

![image](https://user-images.githubusercontent.com/54250441/217121568-dd4cd4fe-aa88-4bb3-bdb7-09e3e7109ab2.png)

**Comment by pckc** [comment]
Tried the @jesugq solution on v1.1.15 and still have the crossed bullet points and doubles on nested bullets.


![Obsidian_rmafIaYQGc](https://user-images.githubusercontent.com/54250441/222566282-c04d749a-55aa-4d35-9491-be641ffaab8c.png)

**Comment by ceciliamay** [comment]
Thanks for the input guys - especially @jesugq ! I'm thinking this is probably fixed with the new Obsidian update, I just need to update the theme so that it doesn't override the Obsidian code. Mockup is done. Coding it now.
