### ISSUE TITLE
Left menu is shifted to right

### ISSUE THREAD

**Issue by ikslavok** [primary-theme/obsidian#169]
It's best if I just show you an image.

![Screenshot_20221105-064953.jpg](https://user-images.githubusercontent.com/16413235/200105088-842bc61b-b917-44c4-9937-0c9775bfff84.jpg)

This appears on my OnePlus 7T PRO
Tried disabling community plugins. Still happening.

**Comment by ceciliamay** [comment]
this issue no longer exists in the refreshed/rebuilt version of Primary! 2.7.0 is compatible across mobile and desktop. consider updating your theme!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/b4e24b18-8934-40d5-aff0-d7bd1c01224d)
