### ISSUE TITLE
Search icon in left column overlaps the text

### ISSUE THREAD

**Issue by Gigafrost** [primary-theme/obsidian#173]
Any way to fix this?

![image](https://user-images.githubusercontent.com/3525107/217016370-0b129fea-546f-402e-83d0-9a972ccba9ff.png)

**Comment by ceciliamay** [comment]
this issue no longer exists in the newly refreshed/rebuilt Primary 2.7.0! consider updating your theme!


![Image](https://github.com/primary-theme/obsidian/assets/90643719/d06c72fe-a4f2-478b-82df-ab68c28f3c0e)
