### ISSUE TITLE
[OBSD-69] Testing Linear <> GitHub Sync

### ISSUE THREAD

**Issue by ceciliamay** [primary-theme/obsidian#181]
<sub>From [SyncLinear.com](https://synclinear.com) | [OBSD-69](https://linear.app/primarytheme/issue/OBSD-69/testing-linear-github-sync)</sub>

**Comment by ceciliamay** [comment]
testing github <> linear sync - comments

**Comment by ceciliamay** [comment]
how about comments from linear?

![psyduck.gif](https://uploads.linear.app/37986067-0e59-400c-9e82-580da6e78f1f/85ac1b9a-4e79-4997-bd76-675b5601a8fe/99a840fc-096c-4f08-ae04-943a0ac8a09f)

**Comment by ceciliamay** [comment]
oh we can reply to a comment???

**Comment by ceciliamay** [comment]
ahhh it just shows up as a normal comment on gh lol

**Comment by ceciliamay** [comment]
let's add a png see if that works 

![obsidian-icon.png](https://uploads.linear.app/37986067-0e59-400c-9e82-580da6e78f1f/7099716e-d0e5-4c05-adb7-2c1d7f5d15d3/3386eaff-de04-448b-9ff9-83aa1ca49fb7)

**Comment by erickvr-dev** [comment]
Finally Cecilia appeared! glad to see you back :)

**Comment by hiimsergey** [comment]
When the world needed her most...

**Comment by ZeFish** [comment]
Oh yeah!!! by the way, coudn't wait, I created this little snippet to have your color back....
https://we.tl/t-bdAM3IS6el
