### ISSUE TITLE
[Primary V2] Lucide chevron-up (in explorer) displayed as a square

### ISSUE THREAD

**Issue by Lisandra-dev** [primary-theme/obsidian#186]
![image](https://github.com/primary-theme/obsidian/assets/30244939/fd4ceeb1-9c0f-4da0-b599-323bcdded03f)

Checked in the css, seems to be caused by `background-color: currentColor` in the big list of svg settings.

**Comment by ceciliamay** [comment]
Is this a plugin? I can't seem to find this one on my end 👀 I can't find a tab that has those set of action buttons.

**Comment by Lisandra-dev** [comment]
No? It appear also on obsidian sandbox... And another user have the bug too.

![image](https://github.com/primary-theme/obsidian/assets/30244939/17c5f93b-35e3-4bd6-afe9-fae443fb6bc3)

**Comment by ceciliamay** [comment]
Ahhh okay I see. It's on Windows as well. Thanks for the extra info! Really helps. I'll look into it

**Comment by Lisandra-dev** [comment]
Oh, maybe it's windows related, yes. I didn't try on my iphone/tablet throught !
