### ISSUE TITLE
CANVAS: CLOUDY TEXT, LOWERCASE ELEMENT

### ISSUE THREAD

**Issue by FREYA265** [primary-theme/obsidian#188]
Hello, here are the display bugs visible on this capture.

![image](https://github.com/primary-theme/obsidian/assets/139784879/10ee96b6-30d3-47ad-82b5-45297aba5d60)

the preview is the problem, because when I'm in input mode, the bug disappears.
![image](https://github.com/primary-theme/obsidian/assets/139784879/811dae4d-4d07-4005-8c1b-69cefefeea5c)

I don't know what the problem is, but at least you're informed.
Thanks

**Comment by ceciliamay** [comment]
thanks for sending this in! quick question - are there any plugins related to canvas that you have turned on?

**Comment by FREYA265** [comment]
Thank you for your reply :) 
Yes there were.
I have deactivated them all to check and the bugs persist :)

**Comment by FREYA265** [comment]
PS: Also, when I change the theme everything works perfectly :)

**Comment by ceciliamay** [comment]
@FREYA265 Thanks for checking that out! last question - what operating system are you on?

**Comment by ceciliamay** [comment]
this one has been solved! it was indeed blurring and the issue was across all platforms. saw it after switching between themes.

will release it in the upcoming beta update this weekend. thank you so much for reporting this @FREYA265 ! 

![Image](https://github.com/primary-theme/obsidian/assets/90643719/3917522d-469e-4c2f-8ecb-26c2c0ec831d)

**Comment by FREYA265** [comment]
@ceciliamay Thank you so much! I'm delighted to have this corrected in the next version.

Also, I don't know if this was seen capture below:

![image](https://github.com/primary-theme/obsidian/assets/139784879/aca1276b-f9ee-4675-9a2a-bce2f5771dae)

The elements are tiny and illegible here :)
Thanks again :)

**Comment by ceciliamay** [comment]
![CleanShot 2024-04-27 at 02 21 11@2x](https://github.com/primary-theme/obsidian/assets/90643719/5670ae46-37f7-4b75-849e-c7d426cb6a5b)

fixed as well for the next release! thanks for sending these in ✨ @FREYA265

**Comment by FREYA265** [comment]
@ceciliamay With great pleasure ^^
thank you very much :3
