### ISSUE TITLE
Lists of links in Properties are a bit too narrow on the left side

### ISSUE THREAD

**Issue by SkepticMystic** [primary-theme/obsidian#190]
I feel like the "pill" should be a bit wider on its left-side

![image](https://github.com/primary-theme/obsidian/assets/70717676/32d32f11-bf64-48d4-9cdf-d0dae0d9ac60)

It only seems to happen for links in the list - they're styled differently.

The raw YAML is:

```yaml
month: ["[[2024-04]]", "something"]
```

**Comment by ceciliamay** [comment]
This one is fixed and ready in the next beta - v2.3.0! Out this weekend.

![Image](https://github.com/primary-theme/obsidian/assets/90643719/3691b625-9b43-4151-96d2-9877c1814c5a)
