### ISSUE TITLE
Numbers in bold are not bold

### ISSUE THREAD

**Issue by dubefab** [primary-theme/obsidian#193]
No more explanation... it's what I get with default theme font.

**Comment by ceciliamay** [comment]
![CleanShot 2024-05-09 at 13 14 26@2x](https://github.com/primary-theme/obsidian/assets/90643719/ca416541-8a76-412c-bcb1-06f09e42e513)

hmmm... seems to be working correctly 👀 this is in live preview. i've also checked reading mode and source mode and they look just like above. may i ask what is your OS? what version of the theme you are using? (most current is 2.3.0-beta!)

**Comment by dubefab** [comment]
Never mind, I had some Hindi font that it picked up only for numbers 🙈

**Comment by ceciliamay** [comment]
hahaha i see!! thanks for reporting anyway - glad you were able to figure it out! 🙏
