### ISSUE TITLE
Selecting more than 1 note in sidebar

### ISSUE THREAD

**Issue by dubefab** [primary-theme/obsidian#194]
If I select a note in the sidebar, it becomes lighter so that I know which one I selected, use shift or cmd to select more, they are all just the normal color, no way to know which ones were selected.

**Comment by ceciliamay** [comment]
fixed it! thank you for posting. already fixed the bug! update will be out this week's beta!

![CleanShot 2024-05-10 at 03 09 59](https://github.com/primary-theme/obsidian/assets/90643719/80f55306-5158-469d-96bc-bcea7ed79cd7)
