### ISSUE TITLE
FR: Different checkbox styles

### ISSUE THREAD

**Issue by SkepticMystic** [primary-theme/obsidian#196]
Hey :)
I see #170 exists, but is more of a bug than an FR.

I'd like for there to be styling for alternate checkbox states, for example:

`- [/] In progress`
`- [?] Waiting on question`

Interestingly, the Tasks plugin recognises these alternate states from different themes, perhaps you can expose them in the same way to integrate with the plugin:

![image](https://github.com/primary-theme/obsidian/assets/70717676/dcfa7839-a096-47ea-8aa8-a5d9f8d7cb36)

**Comment by HynDuf** [comment]
I would love this (many checkbox styles like AnuPpuccin theme)

**Comment by Krakor92** [comment]
Ditto! As a user of the first version of Primary, I was surprised that it hasn't been ported with this v2. I'm very glad to see that it is **In Progress** now 😄

**Comment by ceciliamay** [comment]
checkbox styles / checkbox icons / alternative checkboxes are now available in v2.8.0! please update your theme :) 
2.8.0 comes with colorful folders, with different styling options and fully customizable.
[click here for the complete release notes!](https://github.com/primary-theme/obsidian/releases/tag/v.2.8.0)

thank you all for reporting and pitching in!! 🙏
