### ISSUE TITLE
Color sidebar

### ISSUE THREAD

**Issue by dubefab** [primary-theme/obsidian#197]
You might wanna either go white font or tone down the darkness of colors in the browser... see screenshot.
![2024-05-10_16 34 03](https://github.com/primary-theme/obsidian/assets/36094769/94bc2f5f-aece-479a-a25e-e4510bb7b4fe)

**Comment by ceciliamay** [comment]
Hmm... this is how it looks like on my end:
![CleanShot 2024-05-11 at 07 02 00@2x](https://github.com/primary-theme/obsidian/assets/90643719/ba44982e-3a4c-40f2-9b41-e611eaa884ef)

It's been this way since the first 2.0 beta version, and I haven't had this kind of issue 🤔

**Comment by ceciliamay** [comment]
Can you check if it might be some external issue on your end? i.e. snippets, plugins. Maybe reloading Obsidian might work as well? Can't seem to replicate this unless I change the code 👀 Also doesn't no problems in v1.6 of Obsidian

**Comment by dubefab** [comment]
weird... there's no snippets!! and i'm on stable version. I restarted it.

**Comment by ceciliamay** [comment]
I see 👀 I'll check it out next week and if I find the issue I'll send in a solution in the 2.5.0 beta release -- I've already prepared for 2.4.0 and will be out tomorrow so can't work on it as immediately. Thanks for reporting this!

**Comment by FREYA265** [comment]
Hi @dubefab , I think you should have added the css as a snippet rather than as a theme. That should fix it :) @ceciliamay

**Comment by dubefab** [comment]
Ok I tried it, doesn't change anything!

**Comment by dubefab** [comment]
Nope it doesn't help :(

**Comment by ceciliamay** [comment]
i have some details i'd like to ask:
- what is your current obsidian version?
- what is the version of your installer? (should be below the obsidian version)
- what OS are you using and what version of the OS are you on?

**Comment by dubefab** [comment]
Actually you made me think.. I was running 1.5.12 under 1.5.3 installer, I just installed with 1.5.12 installer.. but no change.
I'm on latest as of yesterday's update: macOS Sonoma 14.5 (23F79)

**Comment by dubefab** [comment]
hey it's fixed! No idea why haha

**Comment by ceciliamay** [comment]
hey that's great to hear!! thanks for the update. i'll close this now.
