### ISSUE TITLE
fix: Some Lucide icons render as a blank cube

### ISSUE THREAD

**Issue by SkepticMystic** [primary-theme/obsidian#198]
Obsidian now ships with [Lucide icons](https://lucide.dev) built-in for plugin-devs to use. In Primary, specifically, most of them work fine, but some seem to render as a filled-in cube. For example, in the Breadcrumbs plugin, the Lucide `ChevronsUpDown` icon (bottom row, in the middle):

![image](https://github.com/primary-theme/obsidian/assets/70717676/62e8d9c6-c535-479b-97d0-fd09743c64db)

Here is the SVG, if it helps:

```html
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide-icon lucide lucide-chevrons-up-down ">
  <path d="m7 15 5 5 5-5"></path>
  <path d="m7 9 5-5 5 5"></path>
</svg>
```

**Comment by ceciliamay** [comment]
@SkepticMystic is this on the latest 2.4.0-beta?

**Comment by SkepticMystic** [comment]
Ahh, it's fixed in the latest :D

**Comment by ceciliamay** [comment]
yay!! alright - i'll close this one now thanks for posting nonetheless!
