### ISSUE TITLE
Launch progress on Window 11

### ISSUE THREAD

**Issue by dannuen** [primary-theme/obsidian#199]
Hi,

Thank you for your good work!

There’s a strange issue with the launch progress on my Windows 11. However, I don’t have any active snippets.

https://github.com/primary-theme/obsidian/assets/111210530/7ea57f7c-f3fa-405f-9f0a-52df4fddc8c5

**Comment by ceciliamay** [comment]
hello! i redesigned the launch progress actually, so that is by design (i removed the loading title) 😅 but considering your comment, i decided to bring back the title for this week's beta, and the green loading bar to an orange.

**Comment by dannuen** [comment]
Hi, upon re-reading my comment, I realize that I wasn’t clear about the issue. To clarify, is the dot at the end of the launch progress supposed to be there?

![Screenshot 2024-05-17 142347](https://github.com/primary-theme/obsidian/assets/111210530/7694f296-d4d1-43f0-92e9-146ed322fd6a)

**Comment by ceciliamay** [comment]
thanks for clarifying! definitely the dot shouldn't be there. i'll look into it! thanks for posting.

**Comment by ceciliamay** [comment]
i think this is fixed in the latest release! btw, Primary 2.7.0 is now out for the public and available in the theme store!
