### ISSUE TITLE
Suggestion - Colored Folders

### ISSUE THREAD

**Issue by Lmasey** [primary-theme/obsidian#200]
I am loving the changes that come out each week! I am hoping that we will see colored folders. The side panel needs a little color:)

**Comment by ceciliamay** [comment]
hello @Lmasey ! colored folders is now available in v2.8.0! [visit this link complete release notes](https://github.com/primary-theme/obsidian/releases/tag/v.2.8.0). will be closing this issue now - thanks for reporting!! 🙏
