### ISSUE TITLE
Difficult to see selected text vs unselected text

### ISSUE THREAD

**Issue by SkepticMystic** [primary-theme/obsidian#202]
Related to #66, but not just for highlighted text.

The contrast for selected text in the editor is quite low, making it difficult to tell what exactly is selected. Dark mode is better:

![image](https://github.com/primary-theme/obsidian/assets/70717676/140f50d2-438b-49ab-8b2d-5cde733dada6)

But light mode is particularly difficult:

![image](https://github.com/primary-theme/obsidian/assets/70717676/98202b01-6b05-4b5b-bdb6-bc548a758ffd)

**Comment by ceciliamay** [comment]
![CleanShot 2024-05-22 at 15 29 37@2x](https://github.com/primary-theme/obsidian/assets/90643719/84731f14-e13b-44a2-97b4-68ca3ee0116e)


![CleanShot 2024-05-22 at 15 28 59@2x](https://github.com/primary-theme/obsidian/assets/90643719/65c477b1-675c-4efb-aa91-61f2df5980fb)

would this be better? or is it too light?

**Comment by SkepticMystic** [comment]
Haha that seems even harder to tell 😅 it might just be my screen, but I literally cannot see what text you have selected there

**Comment by ceciliamay** [comment]
i think it's very faint myself haha! what do you think about inverting the colors?

![Image](https://github.com/primary-theme/obsidian/assets/90643719/b9360de4-21e4-4b14-89f7-bda37432efbc)

![Image](https://github.com/primary-theme/obsidian/assets/90643719/72c3d918-6103-4e11-9611-e182cf1502b1)

**Comment by SkepticMystic** [comment]
Woh, that's certainly more readable! Perhaps too intense tho, as you say. Ummm I kinda like it? I personally wouldn't be offended at the change, but I also don't know what the phrase "design language" means, so grain of salt :p

I checked on a different device, and can confirm that my original screen is particularly bad at contrast. It's _easier_ to read on mobile.

**Comment by ceciliamay** [comment]
Noted hehe! I'm still iterating on this and came up with these. I'm thinking that the one below seems to be a mix of both original and the iteration above? what do you think?

![CleanShot 2024-05-24 at 11 56 48@2x](https://github.com/primary-theme/obsidian/assets/90643719/26fad66c-94dc-4029-829e-c26be7a1edb7)

![CleanShot 2024-05-24 at 11 57 53@2x](https://github.com/primary-theme/obsidian/assets/90643719/a4a4263b-4043-44be-9c6d-37099d93d9a7)

**Comment by SkepticMystic** [comment]
Nice yeah, those are much clearer, and not too intense. I'd argue for a _smidge_ more contrast (particularly in dark mode), but this is much better

**Comment by ceciliamay** [comment]
thought so too! just increased a lil more contrast for dark mode. will add it to the next release! thank you so much for your input 🙏

**Comment by SkepticMystic** [comment]
Awesome, thank you :)
