### ISSUE TITLE
Inline math ($formula$) is displayed on one line

### ISSUE THREAD

**Issue by FREYA265** [primary-theme/obsidian#203]
Hello Cécilia :)

Inline math ($formula$) is displayed on one line because of the following CSS:
```
mjx-math {
  width: 100%;
}
```

This shouldn't happen, only the `$$x$$` should be on one line!
Thanks again

**Comment by ceciliamay** [comment]
okay saw this and fixed it! should be good on the next release!

![CleanShot 2024-05-24 at 20 41 58](https://github.com/primary-theme/obsidian/assets/90643719/a44f10f2-4924-47e5-ba19-dea24700f286)

the `width: 100%` was originally a fix for reading mode where the math block would scroll past the readable line width. so i used a better target selector for the fix! thanks for sending in the report 🫶
