### ISSUE TITLE
left margin and overlap with relative line numbers

### ISSUE THREAD

**Issue by esodesod** [primary-theme/obsidian#206]
Really love ❤️ the Primary theme -- so hopefully this can assist making it (even) better (and not more work 🙈). Please let me know if I can assist test/verify!

**Findings:**
Seems like the relative line numbers in the left margin (in the editor) overlap a bit while using the [relative line numbers plugin](https://github.com/nadavspi/obsidian-relative-line-numbers), which I use extensively, in combination with "Vim mode".

**Screenshot while testing theme-rebuild:**
![image](https://github.com/primary-theme/obsidian/assets/9432339/8dfcf069-b0c7-4fd3-93c4-42a9f0d8f981)

**Screenshot using default theme:**
![image](https://github.com/primary-theme/obsidian/assets/9432339/83ddd908-0096-4b4f-8961-87e5aaeb383b)

**Comment by ceciliamay** [comment]
hey there @esodesod ! thanks for posting this. wanted to ask if this only occurs in vim mode? what other edge cases does this occur? i'm not comfortable with vim mode yet hence i wanted to ask if you can test it on your end 😅 working on this for the next release.

**Comment by esodesod** [comment]
Hi!

Seems like you don't need Vim mode to reproduce -- I guess this is (mainly) an issue with the combination of (dynamic) left margin from Primary theme, disabling the setting "readable line length" (from Obsidian) and the relative line numbers plugin, causing a slightly offset in the editor.

I've reproduced using the sandbox vault, and created a [short clip to illustrate](https://www.dropbox.com/scl/fi/pcotbq1030gn2e3lp0err/2024-08-01-obsidian-theme-primary-and-relative-line-numbers-Screen-Recording-2024-08-01-at-12.19.22.mov?rlkey=jf5wjeivyzsp5zg7mvwkc53ie&dl=0).

The following configuration is performed after starting the sandbox vault:
- in settings > appearance > install and use primary theme
- in settings > community plugins > install and enable relative line numbers plugin
- in settings > editor, enable the "show line numbers"
- in settings > editor, disable the "readable line length"


Issue seems to always appear when using full screen. If window is resized (smaller) to a specific size, the numbers seems to align better (correct), but resizing more than e.g. 50% of screen size, the relative numbers / margin changes, and issue appears again. I'm usually always in fullscreen, hence issue is always present.

Just let me know if I should add some details in the steps to reproduce, or test anything else :-).

**Comment by ceciliamay** [comment]
this has been fixed for the upcoming 2.9.0 beta! will be closing this now 🥳
