### ISSUE TITLE
Collapse Icons on Headers + Headers in View Mode issue

### ISSUE THREAD

**Issue by cldream95** [primary-theme/obsidian#208]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

No

### Primary Theme Version

v2.7.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Primary v2.7.0
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

Hi ! :) When I activate the "obsidian" snippet to access headers customization, the subfolders move to the right every time I touch folders, notes etc. And the arrows for opening files are on the file name. (photos 3, 4, 5 & 6) But when the "obsidian" snippet is not activated, there's no problem. (photo 1 & 2)

![1](https://github.com/primary-theme/obsidian/assets/174716249/76ad94c0-bab5-4952-85b7-85c620db64e5)
![2](https://github.com/primary-theme/obsidian/assets/174716249/68302b1e-b115-42f7-9dcf-a0931374e71e)
![3](https://github.com/primary-theme/obsidian/assets/174716249/2680ba81-50ee-4a1b-b1a9-c99019b208b0)
![4](https://github.com/primary-theme/obsidian/assets/174716249/eca41b1d-650d-420e-9f5e-a78765f90f36)
![5](https://github.com/primary-theme/obsidian/assets/174716249/c6c3cf58-88ee-4093-98f4-79ab453ae466)
![6](https://github.com/primary-theme/obsidian/assets/174716249/88e460da-ab5a-4172-a74f-6a2aab2ab616)

### Additional Info

It's only with the "obisidian" snippet (obsidian.css)
Thank you !!

**Comment by cldream95** [comment]
Oh, I think I've resolved my problem haha

**Comment by ceciliamay** [comment]
the obsidian snippet is an old version of the theme meant for legacy obsidian users using obsidian v.15.0 and below (but actually it also doesn't work properly haha!). the obsidian.css snippet is actually not needed! feel free to delete it.

as long as the theme is downloaded from the theme store, you're good to go. headers customization for Primary v2.7.0 is available by using [Style Settings plugin](obsidian://show-plugin?id=obsidian-style-settings).

![CleanShot 2024-07-05 at 09 10 04@2x](https://github.com/primary-theme/obsidian/assets/90643719/d9454ce6-7a95-4e21-bab9-67e52b721d37)

**Comment by cldream95** [comment]
Oh thank you for the precision !! For the file's "arrows" it's good, but the title isn't well placed with the theme :( I already change the settings. And when I'm on view mode, it made something strange
![image_2024-07-07_230812710](https://github.com/primary-theme/obsidian/assets/174716249/08790d78-c738-43e2-8823-28781d0fd4df)
![image_2024-07-07_231702414](https://github.com/primary-theme/obsidian/assets/174716249/9b4d9ffc-fce7-4d92-a00f-4a438539b8d3)

**Comment by ceciliamay** [comment]
will look into it after this week's update! thank you so much for reporting 🙏

**Comment by ceciliamay** [comment]
hey there @cldream95 ! wanted to touch base on this and ask if this issue is still occurring? i investigated it on my end today and the issue doesn't seem to occur on my end.

if it's still showing up, can you kindly update the theme to the latest version v2.8.0 and check if any plugins or snippets affecting this? don't forget to restart the obsidian app after updating to ensure you're running it fresh! i will be closing the theme in a few days if there's no reply (cleaning up the tasks board!).
