### ISSUE TITLE
Way to increase the interface font size, sidebar ribbon icons size, and monospace font sizee

### ISSUE THREAD

**Issue by stahpdat** [primary-theme/obsidian#217]
### Primary Theme Version

2.7.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.4.13
	Operating system: Windows 10 Home Single Language 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Primary v2.7.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Style Settings v1.0.8
		2: Leaflet v6.0.5
		3: Solo RPG Toolkit v0.3.23
		4: Excalidraw v2.2.7
		5: Various Complements v10.0.0
		6: Homepage v4.0.2
		7: Folder notes v1.7.22

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the enhancement

It's hard to see the icons and the interface text because they're small. It'd be nice if there was a way to make them bigger.
![Screenshot (1343)](https://github.com/user-attachments/assets/4b43baee-3759-41d9-85a8-26892f10faef)
An example of how big my body text normally is so that I can see and write comfortably in dark mode. The icons and the interface text is significantly smaller, which is hard to read.

**Theme that provides a way to increase size**
[ITS Theme](https://publish.obsidian.md/slrvb-docs/ITS+Theme/ITS+Theme) | Under Workspace, there's an option called Sizes where you can select among Readable (medium size), Minimized (tiny), and Large (big).  Under Workspace then under Sidebar, there are options to edit the sidebar font size and the sidebar ribbon icon size, among others.

**Comment by ceciliamay** [comment]
hi there!

these sound like they could be solved by increasing the interface size - a built in customizable option from obsidian. you can increase the interface size by going to settings > appearance tab > and under the advanced section, adjust the **zoom level**.

**Comment by ceciliamay** [comment]
the commit above adds ribbon icon size customizability, and i've added interface font size adjustability. i will add an option to manually adjust the monospace font size when i release customization option for inline code and codeblocks in the near future :) for now i will close this. the others are ready for 2.10.0-beta release this weekend.

thanks for the suggestion! 🙏
