### ISSUE TITLE
Close button of the in-note search bar shows two "x"s

### ISSUE THREAD

**Issue by oxdc** [primary-theme/obsidian#220]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.7.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 23.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Primary v2.7.0
	Snippets enabled: 16
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 19
		1: List Callouts v1.2.7
		2: Advanced Tables v0.21.0
		3: Auto Link Title v1.5.4
		4: Calendar v1.5.10
		5: Contextual Typography v2.2.5
		6: Copy Block Link v1.0.4
		7: Underline v1.3.0
		8: Style Settings v1.0.8
		9: Smart Typography v1.0.18
		10: Paste URL into selection v1.7.0
		11: Outliner v4.8.1
		12: Obsidian Toolkit v0.2.2
		13: Minimal Theme Settings v8.0.2
		14: Kanban v2.0.51
		15: Latex Suite v1.9.4
		16: Git v2.24.3
		17: Links v1.17.7
		18: Custom File Explorer sorting v2.1.11
		19: Vertical Tabs v0.1.0

### Share the Steps to Reproduce the Bug

Cmd+F to open the in-note search bar.

### Additional Info

<img width="640" alt="image" src="https://github.com/user-attachments/assets/5b9cfe4a-d0f1-48f5-b4a3-a16d9ce87321">

The "close" button of the search bar is broken.

**Comment by ceciliamay** [comment]
thanks for reporting! this is a similar issue to #216 and has already been fixed in the 2.8.0-beta! i will close this now.

![CleanShot 2024-07-25 at 19 43 21@2x](https://github.com/user-attachments/assets/2593b319-0940-440b-83ff-fac05103c87b)
