### ISSUE TITLE
Bad performance in popups blur

### ISSUE THREAD

**Issue by Rikiub** [primary-theme/obsidian#221]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.7.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Primary v2.7.0
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Image Context Menus v1.9.0
		2: File Cleaner Redux v1.0.0
		3: Emoji Autocomplete v1.4.1
		4: Dataview v0.5.67
		5: Auto Link Title v1.5.4
		6: Auto Embed v1.1.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

- Open: _**Settings**/**Command Palette**/**Quick Switcher**/**Anything with popups**_

### Additional Info

Maybe it only happens on **low-end PCs**, but the performance is unacceptable.
In general, blurring effects in **CSS** perform poorly.

Maybe it's better to keep it disabled and keep it as optional in [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings)?

**Comment by ceciliamay** [comment]
hey there! 

while one of Primary's goal is to keep it as performant as possible (considering its aesthetic), I decided to opt for keeping the blur default. observing primary's user type over the years has given me insight that most of primary's users just want a theme out of the box with little to know customization required. some don't install style settings as well - or any plugin. most computers nowadays should be able to handle it - which is also why i decided to keep it, but i agree that there should be an easy way to remove this!

i have decided with two approaches:
1. i will give an option to remove the blur via style settings (for those who have the plugin)
2. i will give a snippet that users can add to remove the blur (for those who don't use plugins). this will be posted on the documentation site.

what do you think of the solution? either way i have planned to do no. 1 even before so i will add it now. but what do you think of the two approaches?
