### ISSUE TITLE
Primary Mobile - Folder Icon Graphical Issue

### ISSUE THREAD

**Issue by LocalEldritchHorror** [primary-theme/obsidian#228]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

No

### Primary Theme Version

v.2.8.0

### Debug Info

SYSTEM INFO:
	Operating system: android 14 (samsung SM-S918U1)
	Obsidian version: 1.6.5 (147)
	API version: v1.6.5
	Login status: not logged in
	Live preview: on
	Base theme: dark
	Community theme: Primary v2.8.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

![Screenshot_20240804_000724_Obsidian](https://github.com/user-attachments/assets/e995c06c-3319-4c84-90e3-c0c3904870fb)

1. Go to Style Settings
2. Enable folder icons

### Additional Info

The folder icons on mobile have weird bits below them

**Comment by ceciliamay** [comment]
this issue has been fixed along and is similar with #223 - public version will be out soon!
