### ISSUE TITLE
The Excalidraw canvas moves up when I right click on a drawing element to show the context menu

### ISSUE THREAD

**Issue by kkriszt** [primary-theme/obsidian#229]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Primary v2.8.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

1. Open an Excalidraw file
2. Select a drawing element
3. Right click for contextual menu

https://github.com/user-attachments/assets/ff675a6b-d5cb-4213-a24f-a674cd40dd37

**Comment by ttodosi** [comment]
thats a bugger

**Comment by ceciliamay** [comment]
hey there @kkriszt ! currently investigating this.

can you check if this is still occurring? the issue doesn't seem to be showing up on my end. if it is still persistent, can you also try updating excalidraw and see an update fixes it? let me know how it goes.

**Comment by kkriszt** [comment]
hi @ceciliamay! I just checked with the latest obsidian and excalidraw plugin updates and the problem is gone! Thanks for the investigation and the fantastic theme, I love it!

**Comment by ceciliamay** [comment]
yay!!! thanks for the prompt reply. will close this now ✨
