### ISSUE TITLE
Mobile device folder icon issue

### ISSUE THREAD

**Issue by foodgy** [primary-theme/obsidian#230]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 23.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: light
	Community theme: Primary v2.8.0
	Snippets enabled: 10
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 7
		1: Calendar v1.5.10
		2: Dataview v0.5.67
		3: Heatmap Calendar v0.7.1
		4: Meta Bind v1.1.3
		5: Omnivore v1.10.4
		6: Style Settings v1.0.8
		7: Templater v2.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

This is how folder icons look like on Primary 2.8.0 (tested without plugins).
iPhone 14 Pro Max.

![photo_2024-08-05 15 11 48](https://github.com/user-attachments/assets/5040ff45-bf1b-4e88-8cb3-3f2c8fdde834)

**Comment by ceciliamay** [comment]
this has been fixed in the 2.9.0 public release! please update your theme. i will close this now :)
