### ISSUE TITLE
Colourful Bookmarks 

### ISSUE THREAD

**Issue by bwoah-md** [primary-theme/obsidian#231]
### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.12
	Operating system: Windows 10 Home Single Language 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Primary v2.8.0
	Snippets enabled: 109
	Restricted mode: off
	Plugins installed: 43
	Plugins enabled: 42
		1: Fast Text Color v1.0.73
		2: Iconic v1.0.10
		3: Advanced Tables v0.21.0
		4: Better Export PDF v1.8.3
		5: Book Search v0.7.4
		6: BRAT v1.0.1
		7: Callout Manager v1.1.0
		8: Chronology v1.1.11
		9: Style Settings v1.0.8
		10: cMenu v1.1.2
		11: Dataview v0.5.67
		12: Day Planner v0.21.1
		13: Excalidraw v2.3.0
		14: Export Image plugin v2.3.10
		15: Hider v1.4.0
		16: Highlightr v1.2.2
		17: Home tab v1.2.1
		18: DataLoom v8.16.1
		19: List Callouts v1.2.7
		20: Mind Map v1.1.0
		21: Nifty Links v1.3.0
		22: Omnisearch v1.24.0
		23: Open Gate v1.11.6
		24: Page Gallery v0.8.4
		25: Pomodoro Timer v1.2.3
		26: Quick Explorer v0.2.8
		27: Settings Search v1.3.10
		28: Smart Typography v1.0.18
		29: Status Bar Organizer v2.0.2
		30: Snippet Downloader v2.0.1
		31: Surfing v0.9.12
		32: Tabs v1.1.7
		33: Timekeep v1.5.0
		34: Kanban v2.0.51
		35: Discord Rich Presence v1.5.1
		36: Iconize v2.14.3
		37: Advanced Canvas v3.0.6
		38: Optimize Canvas Connections v1.0.0
		39: Dashboard navigator v1.1.1
		40: Smart Connections v2.1.88
		41: Electron Window Tweaker v1.0.8
		42: Banners v1.3.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the enhancement

![image](https://github.com/user-attachments/assets/591744f1-a619-400f-a0c6-b7dc269e231d)

Hey there I would like to suggest to add a "colorful-folder-view" to the bookmarks menu as well.

I am so far satisfied with the colorful folder icons and in my opinion, they are the best...

**Comment by ceciliamay** [comment]
just finished adding this feature in! it's ready for 2.10.0-beta which will be out to supporters this weekend. public release will come soon 😄

**Comment by bwoah-md** [comment]
thank you 👀
