### ISSUE TITLE
Tab Title Bar File Path hidden when tabs are stacked

### ISSUE THREAD

**Issue by naturecodevoid** [primary-theme/obsidian#234]
### Is the bug present in the Default Theme?

No

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Darwin Kernel Version 23.6.0: root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 23.6.0 
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Primary v2.8.0
	Snippets enabled: 15
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

### Share the Steps to Reproduce the Bug

0. Ensure that "Show tab title bar" is enabled in Settings > Appearance > Interface.
1. Enter stacked tab mode.
2. Notice that the file path that is normally shown is not shown.

### Additional Info

While the debug info says that I have 15 snippets enabled, I have none enabled. The issue still occurred if I deleted all my css files. I think it's a bug in Obsidian where snippets that were enabled but deleted are still shown as enabled.

From a quick look in the dev tools, I believe this line is to blame: https://github.com/primary-theme/obsidian/blob/0c93d166f895a33b50b355e94749228ad8d5e816/src/scss/40_editor/_file.scss#L87

Therefore, a quick fix can be made with a snippet:
```css
.mod-root .workspace-tabs.mod-stacked .view-header .view-header-title-container {
  opacity: unset !important;
}
```

**Comment by naturecodevoid** [comment]
Actually, I guess this isn't a bug — the file path reappears on hover. However, it's a bit inconsistent with non-stacked mode, and not very intuitive, as you can probably tell, haha

**Comment by ceciliamay** [comment]
hey @naturecodevoid - thanks for sending this in including your updates!

i don't think i will fix this - the idea was that the file path would be redundant since the title would appear two times (the other being on the side on stacked mode). if you need the file path, it will be there when hovered. i can add an option through style settings in future to toggle this off if others prefer, or change opacities.

thanks for sending this in - gave me an idea/feature to implement in the future!

**Comment by naturecodevoid** [comment]
That makes sense, it would be redundant, but you could argue the same about non-stacked mode.

In regards to the option, I think that would be a great addition, but for something as niche as this it might be overkill.
