### ISSUE TITLE
Can I adjust the line width of the editor in primary?

### ISSUE THREAD

**Issue by xllowl** [primary-theme/obsidian#235]
### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.3
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 23.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Primary v2.8.0
	Snippets enabled: 30
	Restricted mode: off

### Describe the enhancement

Can I adjust the line width of the editor in primary?

**Comment by ceciliamay** [comment]
this one has been added to 2.9.0! beta will come out today, and public version will come out in the weekend 😄
