### ISSUE TITLE
Folder Background Color (Hover), Not updating when edited in style settings.

### ISSUE THREAD

**Issue by Oshizlgzngahr** [primary-theme/obsidian#238]
# Is the bug present in the Default Theme?

No

# Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

# Primary Theme Version

v2.8.0

# Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 23.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Primary v2.8.0
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 21
		1: Tag Wrangler v0.6.1
		2: Style Settings v1.0.9
		3: Better Word Count v0.10.1
		4: Paste URL into selection v1.7.0
		5: Natural Language Syntax Highlighting v0.3.0
		6: Checklist Reset v1.2.1
		7: Mononote v1.2.2
		8: Janitor v1.0.7
		9: Commander v0.5.1
		10: Editing Toolbar v2.4.16
		11: Emoji Toolbar v0.4.1
		12: Plugin Update Tracker v1.5.2
		13: Templater v2.4.2
		14: Settings Search v1.3.10
		15: File Info Panel v1.3
		16: Waypoint v2.1.0
		17: Folder notes v1.7.26
		18: Style Text v0.1.0
		19: Link Embed v2.0.12
		20: Local Backup v0.1.7
		21: Recent Files v1.4.2

# Share the Steps to Reproduce the Bug

1. Install "Style Settings" plugin and Primary Theme
2. Set Theme to "Dark"
3. Go-to Style Setttings' File Explorer Options
4. Enable All toggles at top of File Explorer options. (Folders as Collapse Indicator, Colored Folder Text, etc.)
5. Go to individual settings for one of the folders below.
6. Change the "Background Color when Hovered" to a color other than default for that folder.
7. Hover over corresponding folder in file explorer panel.

## Result:
Color change is not accurately reflected when folder hovered over. Folder either shows no change from default setting (Folders 1-6) or turns to shade of brown (Folders 7 and up) instead of the actual color. (In light theme it turns to beige/orangey tint)

# Screenshots

### No Hover:
![Screenshot 2024-08-31 at 2 02 36 PM](https://github.com/user-attachments/assets/43d4947a-3520-4703-8147-27d4ae3d0da0)

### Hover on Folder 8:
![Screenshot 2024-08-31 at 2 03 46 PM](https://github.com/user-attachments/assets/f09ae0d0-58ac-4ba5-871a-1a57a25fa6f3)

### Hover on Folder 9:
![Screenshot 2024-08-31 at 2 04 07 PM](https://github.com/user-attachments/assets/1380e873-a3bb-4052-a3dc-2e782db4dc27)

# Additional Info

## Here's a table of the custom colors I'm using for Folders 7 - 9
| Folder | Text Color | Collapse Indicator | Background Color | Background Color, Hover | Indentation Guide | Default? |
| ------ | ---------- | ------------------ | ---------------- | ----------------------- | ----------------- | -------- |
| F7     | D650B5     | D650B580           | D650B51F         | D650B515                | D650B540          | N        |
| F8     | 5D80E9     | 5D80E980           | 5D80E91F         | 5D80E915                | 5D80E940          | N        |
| F9     | ED5C77     | ED5C7780           | ED5C771F         | ED5C7715                | ED5C7740          | N        |

## Context notes:
- I haven't disabled all of my plugins troubleshooting this since I'm just getting into obsidian and have some more complex items like Folder Notes and Waypoint in-use and don't want to break my notes. **Though I have tried disabling most of my plugins and/or snippets. Esp. ones I know would affect Obsidians appearance to no avail.**
- I only use the dark theme in this context so most of my troubleshooting has been done there. **Though i did test in the light theme and got similar results. See result note in steps section**
- Folder seems to still be accounting for difference in color to some extent. The three folders I first noticed having this issue (Folders 7, 8 & 9) turn to shades of brown from eachother when I have them set to different colors.
- Setting seems to be handled differently between Folders 1-6 vs 7 and later. I tried applying the colors to one of the earlier folders that I still had on the default settings and there was no change.
- I have a CSS snippet that hides the "Attachments" which primary sees as Folder 1 (Red). So that's why there is not a default red folder in my screenshots at this time. (Was having this issue before I installed the snippet and disabling it has no effect.)
- I don't have enough folders to test all 12 folder slots in the style settings, so I'm not sure how it affects Folders 10 - 12.
- Issue also seems to carry over to any sub-folders that inherit the color settings from the main folder.

## Other troubleshooting I've tried:
- Applied the bg, hover color to the light theme setting for the same folder. **No effect.**
- Tried choosing different colors or shades. **No effect.** (e.x. in one test I set the folder to turn to pure-white with no transparency on hover)
- Tried applying the custom colors I was using to Folders 1-6. Instead of going to a shade of brown, there was no change.
- Tried adjusting the transparency setting to make the color less-transparent. **No effect.**
- Tried disabling all cosmetic plugins and snippets one-by-one. **No effect.**
- Tried reloading Obsidian after saving color changes. **No effect.**

**Comment by ceciliamay** [comment]
hi there!! thanks for reporting this. this was due to some typo hehe my bad 😅. this has been fixed and ready for 2.10.0-beta this weekend (09/15)!
