### ISSUE TITLE
File Explorer folder color cycling only works for the first 9 colors instead of 12

### ISSUE THREAD

**Issue by rcjan** [primary-theme/obsidian#239]
### Is the bug present in the Default Theme?

Yes

### Is the bug present in when all Snippets and Community Plugins are turned off?

Yes

### Primary Theme Version

v2.8.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.8
	Operating system: Windows 10 Home 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Primary v2.8.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v1.0.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Share the Steps to Reproduce the Bug

Install the theme, install the style settings plugin, import the following settings (or set manually):

```
{
  "primary-theme@@alt-folder-icons": true,
  "primary-theme@@colorful-folders_collapse-indicator": true,
  "primary-theme@@colorful-folders_background": true,
  "primary-theme@@colorful-folders_indentation-guide": true,
  "primary-theme@@nav-folder-1-bg-color@@light": "#CAB3EC",
  "primary-theme@@nav-folder-1-bg-color-hover@@light": "#eae1f7",
  "primary-theme@@nav-folder-2-bg-color@@light": "#ADBEF5",
  "primary-theme@@nav-folder-2-bg-color-hover@@light": "#dee5fb",
  "primary-theme@@nav-folder-3-bg-color@@light": "#98C7EE",
  "primary-theme@@nav-folder-3-bg-color-hover@@light": "#d6e9f8",
  "primary-theme@@nav-folder-4-bg-color@@light": "#84D0E6",
  "primary-theme@@nav-folder-4-bg-color-hover@@light": "#ceecf5",
  "primary-theme@@nav-folder-5-bg-color@@light": "#86D5D2",
  "primary-theme@@nav-folder-5-bg-color-hover@@light": "#cfeeed",
  "primary-theme@@nav-folder-6-bg-color@@light": "#97D7BE",
  "primary-theme@@nav-folder-6-bg-color-hover@@light": "#d5efe5",
  "primary-theme@@nav-folder-7-bg-color@@light": "#AFD6AE",
  "primary-theme@@nav-folder-7-bg-color-hover@@light": "#dfefdf",
  "primary-theme@@nav-folder-8-bg-color@@light": "#C9D3A5",
  "primary-theme@@nav-folder-8-bg-color-hover@@light": "#e9eddb",
  "primary-theme@@nav-folder-9-bg-color@@light": "#E0CFA6",
  "primary-theme@@nav-folder-9-bg-color-hover@@light": "#f3ecdb",
  "primary-theme@@nav-folder-10-bg-color@@light": "#ECC0C6",
  "primary-theme@@nav-folder-10-bg-color-hover@@light": "#f7e6e8",
  "primary-theme@@nav-folder-11-bg-color@@light": "#EEA0BB",
  "primary-theme@@nav-folder-11-bg-color-hover@@light": "#f8d9e4",
  "primary-theme@@nav-folder-12-bg-color@@light": "#E1A7D7",
  "primary-theme@@nav-folder-12-bg-color-hover@@light": "#f3dcef"
}
```

### Additional Info

Bug in action (sandbox vault). As can be seen, the 10th color is the 1st again, the 11th the 2nd, etc. Despite 12 different colors being configured.

![image](https://github.com/user-attachments/assets/9f1519a4-1ad0-43b5-a301-1744b4599016)

**Comment by ceciliamay** [comment]
thanks for posting!! this will be available in this week's 2.10.0 beta ✨
