### ISSUE TITLE
the line numbers overlap with the text

### ISSUE THREAD

**Issue by jonasqin** [primary-theme/obsidian#240]
### Primary Theme Version

v2.8.0

### Debug Info

![image](https://github.com/user-attachments/assets/054546c9-0045-47a2-84d0-e69e0c4c71a4)

### Describe the enhancement

First of all, a big thank you! Your plugin is fantastic and looks great; I really love it! However, there is a small issue I hope can be optimized: the line numbers overlap with the text. I tried using a plugin to adjust the editor's width, but it didn't work. I hope you can take note of this issue and fix it. Thank you!

**Comment by ceciliamay** [comment]
hello there! a fix is available for 2.9.0-beta - which i will be releasing public this weekend (09/15). i will close this issue now :)

**Comment by ceciliamay** [comment]
this issue is fixed for 2.9.0 - which is available now for the public!

**Comment by jonasqin** [comment]
thank you!
