### ISSUE TITLE
Indented checkbox icons behave strangely in reading view

### ISSUE THREAD

**Issue by kkriszt** [primary-theme/obsidian#245]
### Primary Theme Version

v.2.9.1

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.7.2
	Installer version: v1.6.5
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Primary v2.9.1
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

### Describe the enhancement

In reading mode, some checkbox icons appear strangely when they are indented under a specific checkbox icon. Their behavior is not consistent, they behave differently depending on which checkbox icon is the parent.

Here are few examples:
![primary-theme-checkbox-glitches-schedule](https://github.com/user-attachments/assets/86ac8bcd-7b64-4404-9519-bec0097a323d)
![primary-theme-checkbox-glitches-in-progress](https://github.com/user-attachments/assets/1919e2ec-608c-42a0-ad65-34db0c14a360)
![primary-theme-checkbox-glitches-question](https://github.com/user-attachments/assets/f02edb42-fba6-45bf-98e8-24678a8425db)

**Comment by ceciliamay** [comment]
woah that's wild. thanks for posting this! i will be investigating this today and will drop some notes so i have one source of truth. 

![CleanShot 2024-09-24 at 15 20 54@2x](https://github.com/user-attachments/assets/ac8549cd-a08b-48c5-8ee0-f2ce9077f66d)

![CleanShot 2024-09-24 at 15 21 38@2x](https://github.com/user-attachments/assets/f25d3662-58c5-4e44-9015-ee28e8516776)

![CleanShot 2024-09-24 at 15 22 14@2x](https://github.com/user-attachments/assets/450a8902-2ca3-4009-bafa-54c2576e9b55)

![CleanShot 2024-09-24 at 15 22 57@2x](https://github.com/user-attachments/assets/1ef7ae94-cb10-4eac-ad41-46cb315a9af3)

![CleanShot 2024-09-24 at 15 23 22@2x](https://github.com/user-attachments/assets/add177dd-f8a0-4297-8989-acb9663743e4)

![CleanShot 2024-09-24 at 15 23 49@2x](https://github.com/user-attachments/assets/a0b9b9ca-7824-4801-adb6-41fbd74ecec5)

![CleanShot 2024-09-24 at 15 24 07@2x](https://github.com/user-attachments/assets/af9b760c-3396-46b2-a542-8ac7e92cb209)

![CleanShot 2024-09-24 at 15 24 26@2x](https://github.com/user-attachments/assets/b6baf7bf-660c-4cb7-b123-79f5577d1baf)

![CleanShot 2024-09-24 at 15 24 43@2x](https://github.com/user-attachments/assets/be3c6ee6-04ad-4871-a9f6-cce5db2d65b8)

![CleanShot 2024-09-24 at 15 25 09@2x](https://github.com/user-attachments/assets/51dc10f5-75bd-4714-88cf-8b9a8a72c7b1)

![CleanShot 2024-09-24 at 15 25 23@2x](https://github.com/user-attachments/assets/2139cfdd-fa5c-40af-b675-df5a67392606)

![CleanShot 2024-09-24 at 15 25 47@2x](https://github.com/user-attachments/assets/f1625cd3-3fd4-4fee-8b55-4a8180427a5e)

![CleanShot 2024-09-24 at 15 26 19@2x](https://github.com/user-attachments/assets/d3627bdf-c0ef-40bc-8df1-892cec10f18e)

- summary: the children checkboxes take in the styling of the parent i.e. the gradient background of the in progress, the rotate transform on resched plane icon and pinned note icon
- [ ] approach: isolate the styling

**Comment by ceciliamay** [comment]
i was able to fix the icons! but i couldn't fix the cancelled checkbox icon applying the strikethrough to its children (the goal was that the strikethrough only applies to that line like in preview). i will try to follow this up with a better solution in the future, but i have pushed the fix for this now. so please try updating your theme :)

**Comment by kkriszt** [comment]
Oh, nice, that was faaaast! 🚀 Thank you very much for designing, developing and maintaining this amazing theme! ❤️
