### ISSUE TITLE
[Excalidraw] Scrollable panel displayed behind icons

### ISSUE THREAD

**Issue by gchwalik** [primary-theme/obsidian#44]
## Details
In excalidraw, a scrollable panel for object attributes is displayed under zoom icons. Does not occur in default obsidian theme.

excalidraw asked to close their issue, recommending it was theme-related and not from their code.

## Environment: 
- iOS 15.1 (2020 iPad Pro 12.9")
- Excalidraw v1.5.16 in Obsidian v1.0.5
- Primary theme (couldn't determine version)

## Video
https://user-images.githubusercontent.com/89762294/149051708-bfde9d0a-50f9-4e5b-9439-0bf37ea502f5.mp4

## Original issue logged here:
https://github.com/excalidraw/excalidraw/issues/4571

**Comment by ceciliamay** [comment]
this issue isn't occuring anymore in the latest updates for all 3 - obsidian, excalidraw, and primary. so i shall close this now. thank you so much for reporting!!
