### ISSUE TITLE
[Enhancement] Make the layout more compact on mobile

### ISSUE THREAD

**Issue by dsent** [primary-theme/obsidian#70]
I'll illustrate this with two screenshots. This is Primary:
![Screenshot_20220215-113130_Obsidian](https://user-images.githubusercontent.com/8774536/154076550-74bb750c-698d-4ca3-a99f-3819384e3583.png)

And this is California Coast:
![Screenshot_20220215-113202_Obsidian](https://user-images.githubusercontent.com/8774536/154076628-2b6f3356-7cce-4785-b82a-067df843c601.png)

As you can see, with CC more files are displayed at the same time, and longer names can be visible. I'm not saying you should aim for their design solutions, as they're very different, but making the sidebars a little bit more compact could be useful, as the screen real estate is limited on mobile.

**Comment by ceciliamay** [comment]
Related #10

**Comment by ceciliamay** [comment]
this has been fixed in the new Primary 2.7.0 refresh/rebuild update!

![Image](https://github.com/primary-theme/obsidian/assets/90643719/6dfc64d7-2695-480e-b611-222782682eb1)
